# Generated by Django 5.0.7 on 2024-07-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddytask', '0003_alter_tasklist_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['id']},
        ),
    ]
