# Generated by Django 5.0.7 on 2024-08-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddytask', '0004_alter_tasklist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.CharField(max_length=500),
        ),
    ]
